---
title: "Unpacking Successful Literacy Interventions: Evidence from Liberia"
date: 2026-06-15
description: This paper examines experimentally the impact of a literacy intervention for primary school students in Liberia, and the main mechanisms underlying this impact.
author:
  - name: Emma Scandolo
    url: https://emmascandolo.github.io
    affiliation: UCL
  - name: Pedro Carneiro
    affiliation: UCL
  - name: Nathalie Lahire
    affiliation: World Bank
  - name: Federico Tagliati
    affiliation: Bank of Spain
pub-info:
  links:
    - name: Paper
      url: ../../papers/EGRA_Liberia_2026.pdf
      icon: bi bi-file-earmark-pdf
format: html
---

## Abstract

This paper examines experimentally the impact of a literacy intervention for primary-school students in Liberia and the mechanisms underlying its effects. The intervention combined intensive teacher training, instructional materials, and coaching with activities designed to increase parental and community engagement. Using a cluster-randomized design and longitudinal assessment data, we find large improvements in reading achievement in treatment schools, with gains increasing over time and reaching up to one standard deviation across key literacy domains. A latent-factor model of skill formation indicates that 43% of the total effect operates through improvements in schooling investments and teaching practices, while a further 13% is explained by increased parental investments. We find no significant effects on numeracy skills, indicating neither spillovers nor crowding out.
