project:
  type: website
  resources:
    - google38788d6a75dcb72f.html
    - robots.txt

website:
  title: "Emma Scandolo"
  site-url: https://emmascandolo.github.io
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: cv.qmd
        text: CV
    #foreground: "#393D3E"
    #background: "#ECECEC"
    search: false
format:
  html:
    theme:
      - default
      - custom.scss
    css: styles.css
    toc: true

editor: visual

publish:
  gh-pages:
    origin: origin
    branch: gh-pages
