---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: Emma Scandolo
css: css/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
emma.scandolo.21\@ucl.ac.uk
:::

## EDUCATION

**PhD -- Economics** <br> *University College London* [*Sep 2021 --- Present*]{.cvdate}

::: print-only
-   Research Interests: Economics of Education, Labor Economics
:::

**MSc -- International Economics** <br> *Erasmus University Rotterdam* [*Sep 2019 --- Sep 2020*]{.cvdate}

**BSc -- Economics & Business Economics** <br> *Erasmus University Rotterdam* [*Sep 2016 --- Jul 2019*]{.cvdate}

## WORK EXPERIENCE {style="page-break-before: always"}

**Research Assistant to Gabriella Conti and Attila Lindner** <br> *University College London* [*Jan 2023 -- October 2025*]{.cvdate}

**Impact Evaluation Intern** <br> *European Bank for Reconstruction and Development (EBRD)* [*Oct 2020 -- Sep 2021*]{.cvdate}

**Impact Evaluation Intern** <br> *Dutch Development Bank (FMO)* [*Jun 2020 -- Oct 2020*]{.cvdate}

**Intern** <br> *UNESCO Organization for Women in Science for the Developing World* [*July 2017 -- Aug 2017*]{.cvdate}

## TEACHING

**University College London** <br> *ECON0024* *2022/23 -- 2023/24 –* <br> *ECON0053* *2022/23 -- 2025/26*

**Erasmus University Rotterdam** <br> *FEB11002X* *2017/18 -- 2019/20 –* <br> *FEB13061* *2019/20*

## CONFERENCES

**2025** UNITO-Collegio Carlo Alberto PhD Workshop in Economics, Association for Comparative Economic Studies Conference and Summer School, Italian Association of Labour Economics (AIEL) Annual Conference, ENTER Jamboree at Stockholm School of Economics, Barcelona School of Economics PhD Jamboree, Universitat Aut`onoma de Barcelona Applied Micro Seminar, IFS Education and Skills Brown Bag Seminar
**2024** UCL PhD Seminar, UCL Applied Micro Research Day
**2023** UCL PhD Seminar

## GRANTS

**International Growth Centre (IGC)** <br> £5,000 *Scoping Fund* [*2024/25*]{.cvdate}
